services:
  auth-service:
    env_file:
      - ${AUTH_ENV_FILE:-../.env.dev}
    environment:
      SERVER_PORT: ${SERVER_PORT:-8081}
    ports:
      - "${AUTH_SERVICE_HOST_PORT:-8082}:${SERVER_PORT:-8081}"
    command: ["--spring.profiles.active=dev"]

  auth-mysql:
    env_file:
      - ${AUTH_ENV_FILE:-../.env.dev}
    volumes:
      - type: bind
        source: ./dev/services/mysql/my.cnf
        target: /etc/mysql/my.cnf
      - type: bind
        source: ./dev/services/mysql/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
