services:
  auth-mysql:
    image: mysql:8.0
    volumes:
      - type: volume
        source: auth-mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: services/mysql/dev/my.cnf
        target: /etc/mysql/my.cnf
      - type: bind
        source: services/mysql/dev/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysqladmin ping -h \"$${MYSQL_HOST}\" -u \"$${MYSQL_USER}\" -p\"$${MYSQL_PASSWORD}\""
      ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth-private
