name: auth-service

services:
  auth-service:
    container_name: auth-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ${ENV_FILE_PATH}
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      MYSQL_URL: jdbc:mysql://auth-mysql:3306/${MYSQL_DB}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      MYSQL_HOST: auth-mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL: ${REDIS_SSL:-false}
      SERVER_PORT: ${SERVER_PORT:-8081}
    command: ["--spring.profiles.active=${SPRING_PROFILES_ACTIVE}"]
    ports:
      - "${SERVER_PORT:-8081}:${SERVER_PORT:-8081}"
    depends_on:
      auth-mysql:
        condition: service_healthy
    networks:
      - app-internal
      - msa-shared
      - service-shared
      - auth-private
      - redis-core

  auth-mysql:
    env_file:
      - ${ENV_FILE_PATH}
    networks:
      - auth-private

volumes:
  auth-mysql-volume:

networks:
  service-shared:
    external: true
    name: ${SERVICE_SHARED_NETWORK:-service-backbone-shared}
  auth-private:
    driver: bridge
  msa-shared:
    external: true
    name: ${MSA_SHARED_NETWORK:-msa-shared}
  redis-core:
    external: true
    name: ${REDIS_NETWORK_NAME:-redis-core}
