auth:
  endpoints-enabled: false
  user-cache-ttl-seconds: ${AUTH_USER_CACHE_TTL_SECONDS:300}
  bearer-prefix: "Bearer "
  refresh-cookie-enabled: true
  refresh-cookie-name: ${AUTH_REFRESH_COOKIE_NAME:refresh_token}
  refresh-cookie-http-only: true
  refresh-cookie-secure: ${AUTH_REFRESH_COOKIE_SECURE:false}
  refresh-cookie-path: /
  refresh-cookie-same-site: Lax
  auto-security: false
  oauth2:
    enabled: false
    authorization-base-uri: /oauth2/authorization
    login-processing-base-uri: /login/oauth2/code/*
  jwt:
    secret: ${AUTH_JWT_SECRET:}
    access-seconds: ${AUTH_ACCESS_EXPIRATION:1200}
    refresh-seconds: ${AUTH_REFRESH_EXPIRATION:30000}

AUTH_ACCESS_COOKIE_SECURE: false
AUTH_ACCESS_COOKIE_SAME_SITE: Lax

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${SSO_GITHUB_CLIENT_ID:}
            client-secret: ${SSO_GITHUB_CLIENT_SECRET:}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - read:user
              - user:email
