#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_ENV_SOURCE="$REPO_ROOT/.env.prod"
DEPLOY_ENV_SOURCE="$REPO_ROOT/deploy/ec2/deploy.env.example"
TARGET_ENV_TEMPLATE="$REPO_ROOT/deploy/ec2/.env.production.example"

extract_keys() {
  sed -n 's/^[[:space:]]*\([A-Za-z_][A-Za-z0-9_]*\)=.*/\1/p' "$1" | sort -u
}

[[ -f "$DEPLOY_ENV_SOURCE" ]] || { echo "Deploy env source not found: $DEPLOY_ENV_SOURCE" >&2; exit 1; }
if [[ ! -f "$APP_ENV_SOURCE" ]]; then
  if [[ -f "$TARGET_ENV_TEMPLATE" ]]; then
    echo "App env source not found, keeping existing EC2 bundle env template: $TARGET_ENV_TEMPLATE"
    exit 0
  fi
  echo "App env source not found: $APP_ENV_SOURCE" >&2
  exit 1
fi

duplicate_keys="$(comm -12 <(extract_keys "$APP_ENV_SOURCE") <(extract_keys "$DEPLOY_ENV_SOURCE") || true)"
if [[ -n "$duplicate_keys" ]]; then
  echo "Duplicate keys found between app env and deploy env sources:" >&2
  printf '%s\n' "$duplicate_keys" >&2
  exit 1
fi

mkdir -p "$(dirname "$TARGET_ENV_TEMPLATE")"

{
  printf '# Generated by ./scripts/sync-ec2-env-template.sh\n'
  printf '# App env source: .env.prod\n'
  printf '# Deploy-only source: deploy/ec2/deploy.env.example\n\n'
  cat "$DEPLOY_ENV_SOURCE"
  printf '\n'
  cat "$APP_ENV_SOURCE"
  printf '\n'
} > "$TARGET_ENV_TEMPLATE"

echo "Synced EC2 bundle env template: $TARGET_ENV_TEMPLATE"
